import { BiLogoWhatsapp } from "react-icons/bi";
import { MdOutlineLocalPhone } from "react-icons/md";
import { MdOutlineEmail } from "react-icons/md";
import { HiOutlineBuildingStorefront } from "react-icons/hi2";
import snap from "../../public/images/snapchat.png";
import hour24 from "../../public/images/24hours.png";
import twitter from "../../public/images/twitter.png";
import youtube from "../../public/images/youtube.png";
import insta from "../../public/images/instagram.png";
import tik from "../../public/images/tiktok.png";
import snapicon from "../../public/images/snapchatc.png";
import twittericon from "../../public/images/twitterc.png";
import youtubeicon from "../../public/images/youtubec.png";
import instaicon from "../../public/images/instagramc.png";
import tikicon from "../../public/images/tiktokc.png";
import whats from "../../public/images/whatsapp.png";
import email from "../../public/images/email.png";
import phone from "../../public/images/hours24.png";
import arrow from "../../public/images/arrow.png";
import whatshand from "../../public/images/whatsapphand.png";
import { MdStarRate } from "react-icons/md";
export const contentUsNav = [
  {
    title: "+966545003143",
    image: whatshand,
    id: 0,
  },
  {
    title: "920005232",
    image: hour24,
    id: 1,
  },
];
export const navMenu = [
  {
    title: "الرئيسية",
    image: "/icons/homew.png",
    ref: "/",
    id: 0,
  },
  {
    title: "البرامج السياحية",
    image: "/icons/flagw.png",
    ref: "/packages",
    id: 1,
  },
  {
    title: "الدليل السياحي",
    image: "/icons/offerw.png",
    ref: "/city-guides",
    id: 2,
  },

  {
    title: "الجولات السياحية",
    image: "/icons/thunderw.png",
    ref: "/tours",
    id: 3,
  },
  {
    title: "فنادق",
    image: "/icons/hotelw.png",
    ref: "/hotel",
    id: 4,
  },
  {
    title: "رحلات بحرية",
    image: "/icons/bootw.png",
    ref: "/packages/cruise",
    id: 6,
  },
];
export const navbar = [
  {
    title: "الرئيسية",
    image: "/icons/home.png",
    ref: "/",
    id: 0,
  },
  {
    title: "البرامج السياحية",
    image: "/icons/flag.png",
    ref: "/packages",
    id: 1,
  },
  {
    title: "الدليل السياحي",
    image: "/icons/offer.png",
    ref: "/city-guides",
    id: 2,
  },
  {
    title: "الطيران",
    image: "/icons/plane.png",
    ref: "/",
    id: 3,
  },
  {
    title: "حجز فنادق",
    image: "/icons/hotel.png",
    ref: "/hotel",
    id: 4,
  },
  {
    title: "تواصل معنا",
    image: "/icons/user.png",
    ref: "/contact",
    id: 7,
  },

  {
    title: "رحلات بحرية",
    image: "/icons/boot.png",
    ref: "/packages/cruise",
    id: 6,
  },

  {
    title: "نبذة عنا",
    image: "/icons/user.png",
    ref: "/",
    id: 8,
  },
  {
    title: "تصميم برنامج سياحي",
    image: "/icons/design.png",
    ref: "/",
    id: 5,
  },
];
export const breadcrumb1 = [
  {
    breadcrumbs: [
      { label: "الرئيسية", path: "/" },
      { label: "البرامج السياحية", path: "/travel-programs" },
      // Add more breadcrumbs as needed
    ],
  },
];
export const programs = [
  // {
  //   breadcrumbs: [
  //     { label: "الرئيسية", path: "/" },
  //     { label: "البرامج السياحية", path: "/travel-programs" },
  //     // Add more breadcrumbs as needed
  //   ],
  //   nav: [
  {
    title: "بوكيت عرض لشخصين",
    image: "/images/trav.jpg",
    locate: "تايلاند",
    day: 6,
    night: 5,
    price: 2550,
    person: 2,
    place_id:8,
    rate: [
      // <MdStarRate />,
      // <MdStarRate />,
      // <MdStarRate />,
      // <MdStarRate />,
      // <MdStarRate />,
    ],
    id: 0,
  },
  {
    title: "بوكيت عرض لشخصين",
    image: "/images/trav.jpg",
    day: 6,
    locate: "تايلاند",
    person: 2,
    night: 5,
    place_id:8,
    price: 2550,
    rate: [
      // <MdStarRate />,
      // <MdStarRate />,
      // <MdStarRate />,
      // <MdStarRate />,
      // <MdStarRate />,
    ],
    id: 1,
  },
  {
    title: "بوكيت عرض لشخصين",
    image: "/images/trav.jpg",
    day: 6,
    night: 5,
    price: 2550,
    // rate: [<MdStarRate />, <MdStarRate />, <MdStarRate />],
    id: 2,
    place_id:8,
    locate: "تايلاند",
    person: 2,
  },
  {
    title: "بوكيت عرض لشخصين",
    image: "/images/trav.jpg",
    day: 6,
    night: 5,
    price: 2550,
    rate: [],
    place_id:8,
    id: 3,
  },
  {
    title: "بوكيت عرض لشخصين",
    image: "/images/trav.jpg",
    day: 6,
    night: 5,
    price: 2550,
    rate: [],
    place_id:8,
    id: 4,
  },
  {
    title: "بوكيت عرض لشخصين",
    image: "/images/trav.jpg",
    day: 6,
    night: 5,
    price: 2550,
    rate: [],
    place_id:8,
    id: 5,
  },
  {
    title: "بوكيت عرض لشخصين",
    image: "/images/trav.jpg",
    day: 6,
    night: 5,
    price: 2550,
    rate: [],
    place_id:8,
    id: 6,
    // },
    // ],
  },
];
export const footbar = [
  {
    title: "اتصل بنا على:",
    titleRes: "اتصل بنا",
    desc: "966545003143+",
    image: phone,
    icon: <MdOutlineLocalPhone />,
    id: 0,
  },
  {
    title: " يمكنك مراسلتنا بالبريد الإلكتروني:",
    titleRes: " البريد الإلكتروني",
    desc: "info@elnagahtravel.com",
    image: email,
    icon: <MdOutlineEmail />,
    id: 1,
  },
  {
    title: "تواصل معنا على الوتساب ",
    titleRes: " الوتساب",
    desc: "966545003143+",
    image: whats,
    icon: <BiLogoWhatsapp />,
    id: 2,
  },
  {
    titleRes: "تفضل بزيارتنا",
    desc: "البحث عن فرع",
    icon: <HiOutlineBuildingStorefront />,
    id: 2,
  },
];
export const offers = [
  {
    title: "عرض استثنائي! قيمة حجزك كنقاط بمحفظتك",
    desc: "لغاية 99.99% كنقاط على إقامتك الشتوية في المم...",
    image: "/images/trav.jpg",
    id: 0,
  },
  {
    title: "اكتشف المملكة في يوم التأسيس",
    desc: "لحّق على الشتاء بخصم لغاية 20% على رحلتك",
    image: "/images/trav.jpg",
    id: 1,
  },
  {
    title: "سافر واكسب النقاط في يوم التأسيس",
    desc: "عرض حصري ليوم التأسيس! لغاية 1،727 ر.س كنقاط",
    image: "/images/trav.jpg",
    id: 2,
  },
  {
    title: "عرض حصري على الفنادق",
    desc: "استمتع بخصم 12% على حجزك الفندقي الأول",
    image: "/images/trav.jpg",
    id: 3,
  },
  {
    title: "مزايا حصرية مع 'الفرسان",
    desc: "اكسب أميال مكافآت الفرسان على حجوزات الفنادق",
    image: "/images/trav.jpg",
    id: 4,
  },
];
export const worldHotel = [
  {
    breadcrumbs: [
      { label: "Home", path: "/" },
      // Add more breadcrumbs as needed
    ],
    nav: [
      {
        title: "فنادق في مكة",
        desc: "",
        image: "/images/makkah.jpg",

        id: 0,
      },
      {
        title: "فنادق في جدة",
        desc: "",
        image: "/images/jeddah.jpg",
        id: 1,
      },
      {
        title: "فنادق في المدينة المنورة",
        desc: "",
        image: "/images/madinamnwarh.jpg",
        id: 2,
      },
      {
        title: "فنادق في الرياض",
        desc: "",
        image: "/images/reyad.jpg",
        id: 4,
      },
      {
        title: "فنادق في القاهرة",
        desc: "",
        image: "/images/cairo.jpg",
        id: 5,
      },
      {
        title: "فنادق  في المنامة",
        desc: "",
        image: "/images/manamh.jpg",
        id: 6,
      },
      {
        title: "فنادق في الخبر",
        desc: "",
        image: "/images/khobr.jpg",
        id: 7,
      },
      {
        title: "فنادق في الدمام",
        desc: "",
        image: "/images/damam.jpg",
        id: 8,
      },
      {
        title: "فنادق  في شرم الشيخ",
        desc: "",
        image: "/images/sharm.jpg",
        id: 9,
      },
      {
        title: "فنادق في لندن",
        desc: "",
        image: "/images/londn.jpg",
        id: 10,
      },
      {
        title: "فنادق في الطائف",
        desc: "",
        image: "/images/taif.jpg",
        id: 11,
      },
      {
        title: "فنادق  في الكويت",
        desc: "",
        image: "/images/kwit.jpg",
        id: 12,
      },
      {
        title: "فنادق في باريس",
        desc: "",
        image: "/images/paris.jpg",
        id: 13,
      },
      {
        title: "فنادق في ابها",
        desc: "",
        image: "/images/abha.jpg",
        id: 14,
      },
      {
        title: "فنادق  في ابوظبي",
        desc: "",
        image: "/images/abodabi.jpg",
        id: 15,
      },
      {
        title: "فنادق  في الدوحة",
        desc: "",
        image: "/images/dawha.jpg",
        id: 16,
      },
      {
        title: "فنادق في عمان",
        desc: "",
        image: "/images/amman.jpg",
        id: 17,
      },
      {
        title: "فنادق  في جزر المالديف",
        desc: "",
        image: "/images/maldif.jpg",
        id: 18,
      },
      {
        title: "فنادق في جازان",
        desc: "",
        image: "/images/jazan.jpg",
        id: 19,
      },
      {
        title: "فنادق  في اسطنبول",
        desc: "",
        image: "/images/istanboul.jpg",
        id: 20,
      },
      {
        title: "فنادق  في بريدة",
        desc: "",
        image: "/images/bridh.jpg",
        id: 21,
      },
      {
        title: "فنادق  في ينبا",
        desc: "",
        image: "/images/yonb3.jpg",
        id: 22,
      },
      {
        title: "فنادق  في بانكوك",
        desc: "",
        image: "/images/bankok.jpg",
        id: 23,
      },
      {
        title: "فنادق في الجبيل",
        desc: "",
        image: "/images/jobil.jpg",
        id: 24,
      },
      {
        title: "فنادق في باكو",
        desc: "",
        image: "/images/bako.jpg",
        id: 25,
      },
      {
        title: "فنادق في الاسكندرية",
        desc: "",
        image: "/images/alex.jpg",
        id: 26,
      },
      {
        title: "فنادق  في تبوك",
        desc: "",
        image: "/images/tabouk.jpg",
        id: 27,
      },
      {
        title: "فنادق  في الجيزة",
        desc: "",
        image: "/images/giza.jpg",
        id: 28,
      },
      {
        title: "فنادق في المحرق",
        desc: "",
        image: "/images/mhraq.jpg",
        id: 29,
      },
    ],
  },
];
export const cards = [
  {
    id: "1",
    variant: "hover",
    front: "Hover",
    back: "Back",
  },
  {
    id: "2",
    variant: "click",
    front: "Click",
    back: "Back",
  },
  {
    id: "3",
    variant: "focus",
    front: "Focus",
    back: "Back",
  },
];
export const footer = [
  {
    title: "اشهر الوجهات السياحية",
    links: [
      {
        link: "المالديف",
        image: arrow,
        id: 0,
      },
      {
        link: "ماليزيا",
        image: arrow,
        id: 1,
      },
      {
        link: "اذربيجان",
        image: arrow,
        id: 2,
      },
      {
        link: "جورجيا",
        image: arrow,
        id: 6,
      },
      {
        link: "تركيا",
        image: arrow,
        id: 3,
      },
      {
        link: "فرنسا",
        image: arrow,
        id: 4,
      },
      {
        link: "وجهات متعددة في أوروبا",
        image: arrow,
        id: 5,
      },
    ],
    id: 0,
  },
];

export const footerhelp = [
  {
    id: 3,
    title: " المساعدة",
    links: [
      {
        link: "اتصل بنا",
        image: null,
        id: 0,
      },
      {
        link: "الأسئلة الشائعة",
        image: null,
        id: 1,
      },
      {
        link: "شكر العملاء",
        image: null,
        id: 2,
      },
    ],
  },
];
export const footersocial = [
  {
    title: "تابعنا على",
    links: [
      {
        link: "انستجرام",
        image: insta,
        icon: instaicon,
        width: "5vw",
        height: "5vw",
        id: 0,
      },
      {
        link: "تويتر",
        image: twitter,
        icon: twittericon,
        width: "5vw",
        height: "5vw",
        id: 1,
      },
      {
        link: "يوتيوب",
        image: youtube,
        icon: youtubeicon,
        width: "7vw",
        height: "5vw",
        id: 2,
      },
      {
        link: " تيك توك",
        image: tik,
        icon: tikicon,
        width: "5vw",
        height: "5vw",
        id: 3,
      },
      {
        link: "سناب شات",
        image: snap,
        icon: snapicon,
        width: "5vw",
        height: "5vw",
        id: 4,
      },
    ],
    id: 1,
  },
];
export const footerlegal = [
  {
    title: "قانوني",
    links: [
      {
        link: "سياسة الخصوصية",
        image: null,
        id: 1,
      },
      {
        link: "الشروط و الأحكام",
        image: null,
        id: 2,
      },
    ],
    id: 2,
  },
];
export const allRoutes = [
  {
    titleLink: "جميع الوجهات",
    routs: [
      {
        link: "مصر",
        image: "/images/egypt.jpg",
        id: 0,
      },
      {
        link: "2مصر",
        image: "/images/egypt.jpg",
        id: 1,
      },
      {
        link: "13مصر",
        image: "/images/egypt.jpg",
        id: 2,
      },
      {
        link: "مصر",
        image: "/images/egypt.jpg",
        id: 3,
      },
      {
        link: "مصر",
        image: "/images/egypt.jpg",
        id: 4,
      },
    ],
    id: 1,
  },
  {
    titleLink: " الوجهات الداخلية",
    routs: [
      {
        link: "انجلترا",
        image: "/images/england.jpg",
        id: 0,
      },
      {
        link: "انجلترا",
        image: "/images/england.jpg",
        id: 1,
      },
      {
        link: "انجلترا",
        image: "/images/england.jpg",
        id: 2,
      },
      {
        link: "انجلترا",
        image: "/images/england.jpg",
        id: 3,
      },
      {
        link: "انجلترا",
        image: "/images/england.jpg",
        id: 4,
      },
    ],
    id: 2,
  },
  {
    titleLink: " الوجهات الخارجية ",
    routs: [
      {
        link: "سويسرا",
        image: "/images/swiss.jpg",
        id: 0,
      },
      {
        link: "سويسرا",
        image: "/images/swiss.jpg",
        id: 1,
      },
      {
        link: "سويسرا",
        image: "/images/swiss.jpg",
        id: 2,
      },
      {
        link: "سويسرا",
        image: "/images/swiss.jpg",
        id: 4,
      },
      {
        link: "سويسرا",
        image: "/images/swiss.jpg",
        id: 3,
      },
    ],
    id: 3,
  },
];
//
//
export const socnav1 = [
  {
    name: "باقات باسعار",
    ref: "/packages/pricePakages",
    id: 1,
  },
  {
    name: "باقات دولية",
    ref: "/packages/worldpackages",
    id: 0,
  },

  {
    name: "باقات الرحلات البحرية",
    ref: "/packages/cruise",
    id: 3,
  },
];
//
//
import { useRouter } from "next/router";

export const socnav2 = () => {
  const router = useRouter();
  const currentPath = router.asPath;

  return [
    {
      name: "شهرالعسل",
      ref: currentPath,
      id: 1,
    },
    {
      name: "عوائل",
      ref: currentPath,
      id: 0,
    },
    {
      name: "Vip",
      ref: currentPath,
      id: 3,
    },
  ];
};

//
// city guides array
export const cityGuides = [
  {
    breadcrumbs: [
      { label: "الرئيسية", path: "/" },
      { label: "دليلك السياحي", path: "/" },
      // Add more breadcrumbs as needed
    ],
    nav: [
      {
        title: "دبي",
        desc: "متعة التسوق والمأكولات الشهية والترفيهة",
        image: "/images/dobai.jpg",
        id: 0,
      },
      {
        title: "جرز المالديف ",
        desc: "جنة استوائية في المحيط الهندي",
        image: "/images/maldif.jpg",
        id: 1,
      },
      {
        title: "تبليسي",
        desc: "ثلوج على قمة الجبال",
        image: "/images/tblycy.jpg",
        id: 2,
      },
      {
        title: "جدة",
        desc: "مدينه ساحلية غرب المملكة العربية السعودية",
        image: "/images/jeddah.jpg",
        id: 4,
      },
      {
        title: "سراييفو",
        desc: "مدينة تاريخية رائعة الجمال بماض ساحر",
        image: "/images/sarefo.jpg",
        id: 5,
      },
      {
        title: " شرم الشيخ",
        desc: "وجهتك للاسترخاء والمغامرة",
        image: "/images/sharm.jpg",
        id: 6,
      },
      {
        title: "أبها ",
        desc: "المدينه المكسوة بالطبيعة الخضراء",
        image: "/images/abha.jpg",
        id: 7,
      },
      {
        title: "الرياض",
        desc: "في الرياض .... شتاء لا ينسى",
        image: "/images/reyad.jpg",
        id: 8,
      },
      {
        title: "الخبر",
        desc: "متعة الشتاء في الخبر",
        image: "/images/khobr.jpg",
        id: 9,
      },
      {
        title: "جنيف",
        desc: "عاصمة السلام وأيقونة اوروبا",
        image: "/images/geneva.jpg",
        id: 10,
      },
      {
        title: "ينبع",
        desc: "لؤلؤة البحر الاحمر واحدى افضل مواقع الغوص والشواطئ الرملية",
        image: "/images/yonb3.jpg",
        id: 11,
      },
      {
        title: "القاهرة",
        desc: "شتاء بنكهة فرعونية",
        image: "/images/cairo.jpg",
        id: 12,
      },
      {
        title: "مدينة الملك عبدالله الاقتصادية",
        desc: "حياة عصرية مليئة بالانشطة ووسائل الترفيه المتنوعة",
        image: "/images/abdallh.jpg",
        id: 13,
      },
      {
        title: "تبوك",
        desc: "مدينة شمال غرب المملكة العربية السعودية",
        image: "/images/tabouk.jpg",
        id: 14,
      },
      {
        title: "لندن",
        desc: "مدينة كل المواسم",
        image: "/images/london.jpg",
        id: 15,
      },
      {
        title: "جازان",
        desc: "واحة مميزة واستثنائية وسط الطبيعية",
        image: "/images/jazan.jpg",
        id: 16,
      },
      {
        title: "مكة المكرمه",
        desc: "قبلة المسلمين",
        image: "/images/makkah.jpg",
        id: 17,
      },
      {
        title: "المدينة المنورة",
        desc: "اول عاصمة في تاريخ الاسلام",
        image: "/images/madinamnwarh.jpg",
        id: 18,
      },
      {
        title: "العلا",
        desc: "الشتاء في العلا لا يشبه اي شتاء",
        image: "/images/elal.jpg",
        id: 19,
      },
      {
        title: "الدمام",
        desc: "شتاء ومغامرات الدمام",
        image: "/images/damam.jpg",
        id: 21,
      },
      {
        title: "موريشيوس",
        desc: "وجهتك المثالية للاسترخاء والراحة",
        image: "/images/mauritius.jpg",
        id: 22,
      },
      {
        title: "فيينا",
        desc: "مدينة النسيم العليل ووجهة للفنون والثقافة",
        image: "/images/vienna.jpg",
        id: 23,
      },
      {
        title: "باكو",
        desc: "وجهة شتوية ممتعة",
        image: "/images/bako.jpg",
        id: 24,
      },
      {
        title: "باريس",
        desc: "مدينة النور والأزياء",
        image: "/images/paris.jpg",
        id: 25,
      },
      {
        title: "سيشل",
        desc: "ملاذ هادئ وسط شواطئ النخيل والمياه الفيروزية",
        image: "/images/seychelles.jpg",
        id: 26,
      },
      {
        title: "ابو ظبي",
        desc: "عاصمة الثقافة والفنون المعمارية والشواطئ الساحرة",
        image: "/images/abodabi.jpg",
        id: 27,
      },
      {
        title: "جاكرتا",
        desc: "وجهة تجمع بين سحر الطبيعة وعراقة التاريخ",
        image: "/images/jakarta.jpg",
        id: 28,
      },
      {
        title: "روما",
        desc: "مهد الحضارات والثقافات ووجهة الفنون",
        image: "/images/rome.jpg",
        id: 29,
      },
      {
        title: "مانشستر",
        desc: "القلب النابض لعشاق الرياضة والفنون والهندسة المعمارية",
        image: "/images/manchester.jpg",
        id: 30,
      },
      {
        title: "بالي",
        desc: "اروع الشواطئ والمناظر الخلابة والمعابد الاثرية العريقة",
        image: "/images/bali.jpg",
        id: 31,
      },
      {
        title: "كوالالمبور",
        desc: "شتاء استوائي",
        image: "/images/kuala_lumpur_.jpg",
        id: 32,
      },
      {
        title: "لنكاوي",
        desc: "موطن الغابات الخلابة والشواطي الساحرة",
        image: "/images/langkawi.jpg",
        id: 33,
      },
      {
        title: "الإسكندرية",
        desc: "الوجة المثالية لعشاق التاريخ والسفارة",
        image: "/images/alex.jpg",
        id: 34,
      },
      {
        title: "عمان",
        desc: "مدينة احتضنت العديد من الحضارات منذ فجر الاسلام",
        image: "/images/amman.jpg",
        id: 35,
      },
      {
        title: "المنامة",
        desc: "عروس الخليج",
        image: "/images/manamh.jpg",
        id: 36,
      },
      {
        title: "بانكوك",
        desc: "مدينة باهرة تجمع الاختلافات في مكان واحد",
        image: "/images/bankok.jpg",
        id: 37,
      },
      {
        title: "اسطنبول",
        desc: "مدينة التنوع",
        image: "/images/istanboul.jpg",
        id: 38,
      },
      {
        title: "غروبنن",
        desc: "وجهة ساحرة وسط طبيعة غناء",
        image: "/images/grobndn.jpg",
        id: 39,
      },
      {
        title: "بوكيت",
        desc: "جزيرة الصفاء والحماس",
        image: "/images/bokit.jpg",
        id: 40,
      },
      {
        title: "طرابزون",
        desc: "اكتشف التاريخ الغني والطبيعة الخلابة",
        image: "/images/trabzon.jpg",
        id: 41,
      },
    ],
  },
];
//
// cruise programes
export const cruisePrograms = [
  {
    nav: [
      {
        title: "٧ ليالٍ | الخليج | إم إس سي فيرتيوزا | الدوحة",
        desc: " قطر . البحرين .الإمارات العربية المتحدة",
        image: "/images/mscF.jpeg",
        id: 1,
      },
      {
        title: "٧ ليالٍ | الخليج | إم إس سي فيرتيوزا ",
        desc: " الإمارات العربية المتحدة . قطر . البحرين",
        image: "/images/mscF.jpeg",
        id: 2,
      },
      {
        title: "٧ ليالٍ | الخليج | إم إس سي أوبرا",
        desc: "  الإمارات العربية المتحدةعمان",
        image: "/images/mcsOpra.jpeg",
        id: 3,
      },
    ],
  },
];
// cruise programes
export const packages = [
  {
    nav: [
      {
        title: "باقات بأسعار محددة",
        desc: "",
        image: "/images/abodabi.jpg",

        id: "pricePakages",
      },
      {
        title: "باقات السياحة الدولية",
        desc: "",
        image: "/images/swiss.jpg",

        id: "worldpackages",
      },

      {
        title: "باقات الرحلات البحرية",
        desc: "",
        image: "/images/jakarta.jpg",

        id: "cruise",
      },
    ],
  },
];
export const packageTypes = [
  {
    nav: [
      {
        title: "شهر العسل",
        desc: "",
        image: "/images/honymonth.jpeg",
        ref: "/packages/pricePakages",
        id: 1,
      },
      {
        title: "عوائل",
        desc: "",
        image: "/images/family.jpeg",
        ref: "/packages/worldpackages",
        id: 2,
      },

      {
        title: "VIP",
        desc: "",
        image: "/images/vip.jpeg",
        ref: "/packages/cruise",
        id: 3,
      },
    ],
  },
];
export const countrys = [
  {
    nav: [
      {
        title: "المانيا",
        desc: "فرانكفورت  .  ميونخ",
        image: "/images/germany.jpg",
        ref: "worldpackages/1",
        packages: [
          {
            nav: [
              {
                title: "بوكيت عرض vip",
                image: "/images/trav.jpg",
                locate: "تايلاند",
                day: 6,
                night: 5,
                price: 2550,
                place_id: 8,
                person: 2,

                rate: [
                  // <MdStarRate />,
                  // <MdStarRate />,
                  // <MdStarRate />,
                  // <MdStarRate />,
                  // <MdStarRate />,
                ],
                type: "vip",
                id: 0,
              },
              {
                title: "بوكيت عرض vip",
                image: "/images/trav.jpg",
                day: 6,
                locate: "تايلاند",
                person: 2,
                night: 5,
                price: 2550,
                place_id: 8,
                rate: [
                  // <MdStarRate />,
                  // <MdStarRate />,
                  // <MdStarRate />,
                  // <MdStarRate />,
                  // <MdStarRate />,
                ],
                type: "vip",
                id: 1,
              },
              {
                title: "بوكيت عرض vip ",
                image: "/images/trav.jpg",
                day: 6,
                night: 5,
                price: 2550,
                place_id: 8,
                // rate: [<MdStarRate />, <MdStarRate />, <MdStarRate />],
                type: "vip",
                id: 2,
                locate: "تايلاند",
                person: 2,
              },
              {
                title: "بوكيت عرض لشخصين",
                image: "/images/trav.jpg",
                day: 6,
                night: 5,
                price: 2550,
                place_id: 8,
                rate: [],
                type: "شهرالعسل ",
                id: 3,
              },
              {
                title: "بوكيت عرض شهر العسل",
                image: "/images/trav.jpg",
                day: 6,
                night: 5,
                price: 2550,
                place_id: 8,
                rate: [],
                type: "شهرالعسل ",
                id: 4,
              },
              {
                title: "بوكيت عرض شهر العسل",
                image: "/images/trav.jpg",
                day: 6,
                night: 5,
                price: 2550,
                place_id: 8,
                rate: [],
                type: "شهرالعسل ",
                id: 5,
              },
              {
                title: "بوكيت عرض العائلة",
                image: "/images/trav.jpg",
                day: 6,
                night: 5,
                price: 2550,
                place_id: 8,
                rate: [],
                type: "عوائل",
                id: 6,
              },
            ],
          },
        ],
        id: 1,
      },
      {
        id: 2,
        title: "قطر",
        desc: "الدوحة ⚪هيلتون  سلوى بيتش اند ريزوريت اند فيلاز⚪ منتجع جزيرة البنانا من انانتارا ⚪",
        image: "/images/qatar.jpg",
        ref: "worldpackages/2",
        packages: [
          {
            nav: [
              {
                title: "بوكيت عرض لشخصين",
                image: "/images/trav.jpg",
                locate: "تايلاند",
                day: 6,
                night: 5,
                price: 2550,
                place_id: 8,
                person: 2,

                rate: [
                  // <MdStarRate />,
                  // <MdStarRate />,
                  // <MdStarRate />,
                  // <MdStarRate />,
                  // <MdStarRate />,
                ],
                type: "vip",
                id: 0,
              },
              {
                title: "بوكيت عرض لشخصين",
                image: "/images/trav.jpg",
                day: 6,
                locate: "تايلاند",
                person: 2,
                night: 5,
                price: 2550,
                place_id: 8,
                rate: [
                  // <MdStarRate />,
                  // <MdStarRate />,
                  // <MdStarRate />,
                  // <MdStarRate />,
                  // <MdStarRate />,
                ],
                type: "vip",
                id: 1,
              },
              {
                title: "بوكيت عرض لشخصين",
                image: "/images/trav.jpg",
                day: 6,
                night: 5,
                price: 2550,
                place_id: 8,
                // rate: [<MdStarRate />, <MdStarRate />, <MdStarRate />],
                type: "vip",
                id: 2,
                locate: "تايلاند",
                person: 2,
              },
              {
                title: "بوكيت عرض لشخصين",
                image: "/images/trav.jpg",
                day: 6,
                night: 5,
                price: 2550,
                place_id: 8,
                rate: [],
                type: "شهرالعسل ",
                id: 3,
              },
              {
                title: "بوكيت عرض لشخصين",
                image: "/images/trav.jpg",
                day: 6,
                night: 5,
                price: 2550,
                place_id: 8,
                rate: [],
                type: "شهرالعسل ",
                id: 4,
              },
              {
                title: "بوكيت عرض لشخصين",
                image: "/images/trav.jpg",
                day: 6,
                night: 5,
                price: 2550,
                place_id: 8,
                rate: [],
                type: "شهرالعسل ",
                id: 5,
              },
              {
                title: "بوكيت عرض لشخصين",
                image: "/images/trav.jpg",
                day: 6,
                night: 5,
                price: 2550,
                place_id: 8,
                rate: [],
                type: "عوائل",
                id: 6,
              },
            ],
          },
        ],
      },
      {
        id: 3,
        title: "البانيا",
        desc: "تيرانا  ⚪ درويس ⚪ ساراندي ",
        image: "/images/albania.jpg",
        ref: "worldpackages/3",
        packages: [
          {
            nav: [
              {
                title: "بوكيت عرض لشخصين",
                image: "/images/trav.jpg",
                locate: "تايلاند",
                day: 6,
                night: 5,
                price: 2550,
                place_id: 8,
                person: 2,

                rate: [
                  // <MdStarRate />,
                  // <MdStarRate />,
                  // <MdStarRate />,
                  // <MdStarRate />,
                  // <MdStarRate />,
                ],
                type: "vip",
                id: 0,
              },
              {
                title: "بوكيت عرض لشخصين",
                image: "/images/trav.jpg",
                day: 6,
                locate: "تايلاند",
                person: 2,
                night: 5,
                price: 2550,
                place_id: 8,
                rate: [
                  // <MdStarRate />,
                  // <MdStarRate />,
                  // <MdStarRate />,
                  // <MdStarRate />,
                  // <MdStarRate />,
                ],
                type: "vip",
                id: 1,
              },
              {
                title: "بوكيت عرض لشخصين",
                image: "/images/trav.jpg",
                day: 6,
                night: 5,
                price: 2550,
                place_id: 8,
                // rate: [<MdStarRate />, <MdStarRate />, <MdStarRate />],
                type: "vip",
                id: 2,
                locate: "تايلاند",
                person: 2,
              },
              {
                title: "بوكيت عرض لشخصين",
                image: "/images/trav.jpg",
                day: 6,
                night: 5,
                price: 2550,
                place_id: 8,
                rate: [],
                type: "شهرالعسل ",
                id: 3,
              },
              {
                title: "بوكيت عرض لشخصين",
                image: "/images/trav.jpg",
                day: 6,
                night: 5,
                price: 2550,
                place_id: 8,
                rate: [],
                type: "شهرالعسل ",
                id: 4,
              },
              {
                title: "بوكيت عرض لشخصين",
                image: "/images/trav.jpg",
                day: 6,
                night: 5,
                price: 2550,
                place_id: 8,
                rate: [],
                type: "شهرالعسل ",
                id: 5,
              },
              {
                title: "بوكيت عرض لشخصين",
                image: "/images/trav.jpg",
                day: 6,
                night: 5,
                price: 2550,
                place_id: 8,
                rate: [],
                type: "عوائل",
                id: 6,
              },
            ],
          },
        ],
      },
      {
        id: 4,
        title: "تركيا",
        desc: "بودروم ⚪ سابانجا ⚪بورصا ⚪اسطنبول⚪ طرابزون⚪ اوزنجول",
        image: "/images/turkey.jpg",
        ref: "worldpackages/4",
        packages: [
          {
            nav: [
              {
                title: "بوكيت عرض لشخصين",
                image: "/images/trav.jpg",
                locate: "تايلاند",
                day: 6,
                night: 5,
                price: 2550,
                place_id: 8,
                person: 2,

                rate: [
                  // <MdStarRate />,
                  // <MdStarRate />,
                  // <MdStarRate />,
                  // <MdStarRate />,
                  // <MdStarRate />,
                ],
                type: "vip",
                id: 0,
              },
              {
                title: "بوكيت عرض لشخصين",
                image: "/images/trav.jpg",
                day: 6,
                locate: "تايلاند",
                person: 2,
                night: 5,
                price: 2550,
                place_id: 8,
                rate: [
                  // <MdStarRate />,
                  // <MdStarRate />,
                  // <MdStarRate />,
                  // <MdStarRate />,
                  // <MdStarRate />,
                ],
                type: "vip",
                id: 1,
              },
              {
                title: "بوكيت عرض لشخصين",
                image: "/images/trav.jpg",
                day: 6,
                night: 5,
                price: 2550,
                place_id: 8,
                // rate: [<MdStarRate />, <MdStarRate />, <MdStarRate />],
                type: "vip",
                id: 2,
                locate: "تايلاند",
                person: 2,
              },
              {
                title: "بوكيت عرض لشخصين",
                image: "/images/trav.jpg",
                day: 6,
                night: 5,
                price: 2550,
                place_id: 8,
                rate: [],
                type: "شهرالعسل ",
                id: 3,
              },
              {
                title: "بوكيت عرض لشخصين",
                image: "/images/trav.jpg",
                day: 6,
                night: 5,
                price: 2550,
                place_id: 8,
                rate: [],
                type: "شهرالعسل ",
                id: 4,
              },
              {
                title: "بوكيت عرض لشخصين",
                image: "/images/trav.jpg",
                day: 6,
                night: 5,
                price: 2550,
                place_id: 8,
                rate: [],
                type: "شهرالعسل ",
                id: 5,
              },
              {
                title: "بوكيت عرض لشخصين",
                image: "/images/trav.jpg",
                day: 6,
                night: 5,
                price: 2550,
                place_id: 8,
                rate: [],
                type: "عوائل",
                id: 6,
              },
            ],
          },
        ],
      },
      {
        id: 5,
        title: "المالديف",
        desc: "",
        image: "/images/maldif.jpg",
        ref: "worldpackages/5",
        packages: [
          {
            nav: [
              {
                title: "بوكيت عرض لشخصين",
                image: "/images/trav.jpg",
                locate: "تايلاند",
                day: 6,
                night: 5,
                price: 2550,
                place_id: 8,
                person: 2,

                rate: [
                  // <MdStarRate />,
                  // <MdStarRate />,
                  // <MdStarRate />,
                  // <MdStarRate />,
                  // <MdStarRate />,
                ],
                type: "vip",
                id: 0,
              },
              {
                title: "بوكيت عرض لشخصين",
                image: "/images/trav.jpg",
                day: 6,
                locate: "تايلاند",
                person: 2,
                night: 5,
                price: 2550,
                place_id: 8,
                rate: [
                  // <MdStarRate />,
                  // <MdStarRate />,
                  // <MdStarRate />,
                  // <MdStarRate />,
                  // <MdStarRate />,
                ],
                type: "vip",
                id: 1,
              },
              {
                title: "بوكيت عرض لشخصين",
                image: "/images/trav.jpg",
                day: 6,
                night: 5,
                price: 2550,
                place_id: 8,
                // rate: [<MdStarRate />, <MdStarRate />, <MdStarRate />],
                type: "vip",
                id: 2,
                locate: "تايلاند",
                person: 2,
              },
              {
                title: "بوكيت عرض لشخصين",
                image: "/images/trav.jpg",
                day: 6,
                night: 5,
                price: 2550,
                place_id: 8,
                rate: [],
                type: "شهرالعسل ",
                id: 3,
              },
              {
                title: "بوكيت عرض لشخصين",
                image: "/images/trav.jpg",
                day: 6,
                night: 5,
                price: 2550,
                place_id: 8,
                rate: [],
                type: "شهرالعسل ",
                id: 4,
              },
              {
                title: "بوكيت عرض لشخصين",
                image: "/images/trav.jpg",
                day: 6,
                night: 5,
                price: 2550,
                place_id: 8,
                rate: [],
                type: "شهرالعسل ",
                id: 5,
              },
              {
                title: "بوكيت عرض لشخصين",
                image: "/images/trav.jpg",
                day: 6,
                night: 5,
                price: 2550,
                place_id: 8,
                rate: [],
                type: "عوائل",
                id: 6,
              },
            ],
          },
        ],
      },
      {
        id: 6,
        title: "جورجيا",
        desc: "تبليسي ⚪ كازييجي ⚪بورجومي ⚪باتومي ",
        image: "/images/Georgia.jpg",
        ref: "worldpackages/5",
        packages: [
          {
            nav: [
              {
                title: "بوكيت عرض لشخصين",
                image: "/images/trav.jpg",
                locate: "تايلاند",
                day: 6,
                night: 5,
                price: 2550,
                place_id: 8,
                person: 2,

                rate: [
                  // <MdStarRate />,
                  // <MdStarRate />,
                  // <MdStarRate />,
                  // <MdStarRate />,
                  // <MdStarRate />,
                ],
                type: "vip",
                id: 0,
              },
              {
                title: "بوكيت عرض لشخصين",
                image: "/images/trav.jpg",
                day: 6,
                locate: "تايلاند",
                person: 2,
                night: 5,
                price: 2550,
                place_id: 8,
                rate: [
                  // <MdStarRate />,
                  // <MdStarRate />,
                  // <MdStarRate />,
                  // <MdStarRate />,
                  // <MdStarRate />,
                ],
                type: "vip",
                id: 1,
              },
              {
                title: "بوكيت عرض لشخصين",
                image: "/images/trav.jpg",
                day: 6,
                night: 5,
                price: 2550,
                place_id: 8,
                // rate: [<MdStarRate />, <MdStarRate />, <MdStarRate />],
                type: "vip",
                id: 2,
                locate: "تايلاند",
                person: 2,
              },
              {
                title: "بوكيت عرض لشخصين",
                image: "/images/trav.jpg",
                day: 6,
                night: 5,
                price: 2550,
                place_id: 8,
                rate: [],
                type: "شهرالعسل ",
                id: 3,
              },
              {
                title: "بوكيت عرض لشخصين",
                image: "/images/trav.jpg",
                day: 6,
                night: 5,
                price: 2550,
                place_id: 8,
                rate: [],
                type: "شهرالعسل ",
                id: 4,
              },
              {
                title: "بوكيت عرض لشخصين",
                image: "/images/trav.jpg",
                day: 6,
                night: 5,
                price: 2550,
                place_id: 8,
                rate: [],
                type: "شهرالعسل ",
                id: 5,
              },
              {
                title: "بوكيت عرض لشخصين",
                image: "/images/trav.jpg",
                day: 6,
                night: 5,
                price: 2550,
                place_id: 8,
                rate: [],
                type: "عوائل",
                id: 6,
              },
            ],
          },
        ],
      },
      {
        id: 7,
        title: "كازاخستان",
        desc: "الماتي ⚪نور السلطان ",
        image: "/images/kazakhstan.jpg",
        ref: "worldpackages/5",
        packages: [
          {
            nav: [
              {
                title: "بوكيت عرض لشخصين",
                image: "/images/trav.jpg",
                locate: "تايلاند",
                day: 6,
                night: 5,
                price: 2550,
                place_id: 8,
                person: 2,

                rate: [
                  // <MdStarRate />,
                  // <MdStarRate />,
                  // <MdStarRate />,
                  // <MdStarRate />,
                  // <MdStarRate />,
                ],
                type: "vip",
                id: 0,
              },
              {
                title: "بوكيت عرض لشخصين",
                image: "/images/trav.jpg",
                day: 6,
                locate: "تايلاند",
                person: 2,
                night: 5,
                price: 2550,
                place_id: 8,
                rate: [
                  // <MdStarRate />,
                  // <MdStarRate />,
                  // <MdStarRate />,
                  // <MdStarRate />,
                  // <MdStarRate />,
                ],
                type: "vip",
                id: 1,
              },
              {
                title: "بوكيت عرض لشخصين",
                image: "/images/trav.jpg",
                day: 6,
                night: 5,
                price: 2550,
                place_id: 8,
                // rate: [<MdStarRate />, <MdStarRate />, <MdStarRate />],
                type: "vip",
                id: 2,
                locate: "تايلاند",
                person: 2,
              },
              {
                title: "بوكيت عرض لشخصين",
                image: "/images/trav.jpg",
                day: 6,
                night: 5,
                price: 2550,
                place_id: 8,
                rate: [],
                type: "شهرالعسل ",
                id: 3,
              },
              {
                title: "بوكيت عرض لشخصين",
                image: "/images/trav.jpg",
                day: 6,
                night: 5,
                price: 2550,
                place_id: 8,
                rate: [],
                type: "شهرالعسل ",
                id: 4,
              },
              {
                title: "بوكيت عرض لشخصين",
                image: "/images/trav.jpg",
                day: 6,
                night: 5,
                price: 2550,
                place_id: 8,
                rate: [],
                type: "شهرالعسل ",
                id: 5,
              },
              {
                title: "بوكيت عرض لشخصين",
                image: "/images/trav.jpg",
                day: 6,
                night: 5,
                price: 2550,
                place_id: 8,
                rate: [],
                type: "عوائل",
                id: 6,
              },
            ],
          },
        ],
      },
      {
        id: 8,
        title: "تايلاند ",
        desc: "بانكوك⚪ بوكيت⚪ كو ساموري",
        image: "/images/tailand.jpg",
        ref: "worldpackages/5",
        packages: [
          {
            nav: [
              {
                title: "بوكيت عرض لشخصين",
                image: "/images/trav.jpg",
                locate: "تايلاند",
                day: 6,
                night: 5,
                price: 2550,
                place_id: 8,
                person: 2,

                rate: [
                  // <MdStarRate />,
                  // <MdStarRate />,
                  // <MdStarRate />,
                  // <MdStarRate />,
                  // <MdStarRate />,
                ],
                type: "vip",
                id: 0,
              },
              {
                title: "بوكيت عرض لشخصين",
                image: "/images/trav.jpg",
                day: 6,
                locate: "تايلاند",
                person: 2,
                night: 5,
                price: 2550,
                place_id: 8,
                rate: [
                  // <MdStarRate />,
                  // <MdStarRate />,
                  // <MdStarRate />,
                  // <MdStarRate />,
                  // <MdStarRate />,
                ],
                type: "vip",
                id: 1,
              },
              {
                title: "بوكيت عرض لشخصين",
                image: "/images/trav.jpg",
                day: 6,
                night: 5,
                price: 2550,
                place_id: 8,
                // rate: [<MdStarRate />, <MdStarRate />, <MdStarRate />],
                type: "vip",
                id: 2,
                locate: "تايلاند",
                person: 2,
              },
              {
                title: "بوكيت عرض لشخصين",
                image: "/images/trav.jpg",
                day: 6,
                night: 5,
                price: 2550,
                place_id: 8,
                rate: [],
                type: "شهرالعسل ",
                id: 3,
              },
              {
                title: "بوكيت عرض لشخصين",
                image: "/images/trav.jpg",
                day: 6,
                night: 5,
                price: 2550,
                place_id: 8,
                rate: [],
                type: "شهرالعسل ",
                id: 4,
              },
              {
                title: "بوكيت عرض لشخصين",
                image: "/images/trav.jpg",
                day: 6,
                night: 5,
                price: 2550,
                place_id: 8,
                rate: [],
                type: "شهرالعسل ",
                id: 5,
              },
              {
                title: "بوكيت عرض لشخصين",
                image: "/images/trav.jpg",
                day: 6,
                night: 5,
                price: 2550,
                place_id: 8,
                rate: [],
                type: "عوائل",
                id: 6,
              },
            ],
          },
        ],
      },
      {
        id: 9,
        title: "اليونان ",
        desc: "ثينا⚪ ميكونوس⚪ سانتوريني",
        image: "/images/greece.jpg",
        ref: "worldpackages/5",
        packages: [
          {
            nav: [
              {
                title: "بوكيت عرض لشخصين",
                image: "/images/trav.jpg",
                locate: "تايلاند",
                day: 6,
                night: 5,
                price: 2550,
                place_id: 8,
                person: 2,

                rate: [
                  // <MdStarRate />,
                  // <MdStarRate />,
                  // <MdStarRate />,
                  // <MdStarRate />,
                  // <MdStarRate />,
                ],
                type: "vip",
                id: 0,
              },
              {
                title: "بوكيت عرض لشخصين",
                image: "/images/trav.jpg",
                day: 6,
                locate: "تايلاند",
                person: 2,
                night: 5,
                price: 2550,
                place_id: 8,
                rate: [
                  // <MdStarRate />,
                  // <MdStarRate />,
                  // <MdStarRate />,
                  // <MdStarRate />,
                  // <MdStarRate />,
                ],
                type: "vip",
                id: 1,
              },
              {
                title: "بوكيت عرض لشخصين",
                image: "/images/trav.jpg",
                day: 6,
                night: 5,
                price: 2550,
                place_id: 8,
                // rate: [<MdStarRate />, <MdStarRate />, <MdStarRate />],
                type: "vip",
                id: 2,
                locate: "تايلاند",
                person: 2,
              },
              {
                title: "بوكيت عرض لشخصين",
                image: "/images/trav.jpg",
                day: 6,
                night: 5,
                price: 2550,
                place_id: 8,
                rate: [],
                type: "شهرالعسل ",
                id: 3,
              },
              {
                title: "بوكيت عرض لشخصين",
                image: "/images/trav.jpg",
                day: 6,
                night: 5,
                price: 2550,
                place_id: 8,
                rate: [],
                type: "شهرالعسل ",
                id: 4,
              },
              {
                title: "بوكيت عرض لشخصين",
                image: "/images/trav.jpg",
                day: 6,
                night: 5,
                price: 2550,
                place_id: 8,
                rate: [],
                type: "شهرالعسل ",
                id: 5,
              },
              {
                title: "بوكيت عرض لشخصين",
                image: "/images/trav.jpg",
                day: 6,
                night: 5,
                price: 2550,
                place_id: 8,
                rate: [],
                type: "عوائل",
                id: 6,
              },
            ],
          },
        ],
      },
      {
        id: 10,
        title: "البوسنه والهرسك",
        desc: "سراييفو ⚪تارتشين⚪ ايجمان⚪ بيهاتش⚪ موستار ⚪",
        image: "/images/Bosnia.jpg",
        ref: "worldpackages/5",
        packages: [
          {
            nav: [
              {
                title: "بوكيت عرض لشخصين",
                image: "/images/trav.jpg",
                locate: "تايلاند",
                day: 6,
                night: 5,
                price: 2550,
                place_id: 8,
                person: 2,

                rate: [
                  // <MdStarRate />,
                  // <MdStarRate />,
                  // <MdStarRate />,
                  // <MdStarRate />,
                  // <MdStarRate />,
                ],
                type: "vip",
                id: 0,
              },
              {
                title: "بوكيت عرض لشخصين",
                image: "/images/trav.jpg",
                day: 6,
                locate: "تايلاند",
                person: 2,
                night: 5,
                price: 2550,
                place_id: 8,
                rate: [
                  // <MdStarRate />,
                  // <MdStarRate />,
                  // <MdStarRate />,
                  // <MdStarRate />,
                  // <MdStarRate />,
                ],
                type: "vip",
                id: 1,
              },
              {
                title: "بوكيت عرض لشخصين",
                image: "/images/trav.jpg",
                day: 6,
                night: 5,
                price: 2550,
                place_id: 8,
                // rate: [<MdStarRate />, <MdStarRate />, <MdStarRate />],
                type: "vip",
                id: 2,
                locate: "تايلاند",
                person: 2,
              },
              {
                title: "بوكيت عرض لشخصين",
                image: "/images/trav.jpg",
                day: 6,
                night: 5,
                price: 2550,
                place_id: 8,
                rate: [],
                type: "شهرالعسل ",
                id: 3,
              },
              {
                title: "بوكيت عرض لشخصين",
                image: "/images/trav.jpg",
                day: 6,
                night: 5,
                price: 2550,
                place_id: 8,
                rate: [],
                type: "شهرالعسل ",
                id: 4,
              },
              {
                title: "بوكيت عرض لشخصين",
                image: "/images/trav.jpg",
                day: 6,
                night: 5,
                price: 2550,
                place_id: 8,
                rate: [],
                type: "شهرالعسل ",
                id: 5,
              },
              {
                title: "بوكيت عرض لشخصين",
                image: "/images/trav.jpg",
                day: 6,
                night: 5,
                price: 2550,
                place_id: 8,
                rate: [],
                type: "عوائل",
                id: 6,
              },
            ],
          },
        ],
      },
      {
        id: 11,
        title: "كرواتيا ",
        desc: "زغرب ⚪ دبروفينك ⚪ سبليت⚪ بليتفيتش",
        image: "/images/Croatia.jpg",
        ref: "worldpackages/5",
        packages: [
          {
            nav: [
              {
                title: "بوكيت عرض لشخصين",
                image: "/images/trav.jpg",
                locate: "تايلاند",
                day: 6,
                night: 5,
                price: 2550,
                place_id: 8,
                person: 2,

                rate: [
                  // <MdStarRate />,
                  // <MdStarRate />,
                  // <MdStarRate />,
                  // <MdStarRate />,
                  // <MdStarRate />,
                ],
                type: "vip",
                id: 0,
              },
              {
                title: "بوكيت عرض لشخصين",
                image: "/images/trav.jpg",
                day: 6,
                locate: "تايلاند",
                person: 2,
                night: 5,
                price: 2550,
                place_id: 8,
                rate: [
                  // <MdStarRate />,
                  // <MdStarRate />,
                  // <MdStarRate />,
                  // <MdStarRate />,
                  // <MdStarRate />,
                ],
                type: "vip",
                id: 1,
              },
              {
                title: "بوكيت عرض لشخصين",
                image: "/images/trav.jpg",
                day: 6,
                night: 5,
                price: 2550,
                place_id: 8,
                // rate: [<MdStarRate />, <MdStarRate />, <MdStarRate />],
                type: "vip",
                id: 2,
                locate: "تايلاند",
                person: 2,
              },
              {
                title: "بوكيت عرض لشخصين",
                image: "/images/trav.jpg",
                day: 6,
                night: 5,
                price: 2550,
                place_id: 8,
                rate: [],
                type: "شهرالعسل ",
                id: 3,
              },
              {
                title: "بوكيت عرض لشخصين",
                image: "/images/trav.jpg",
                day: 6,
                night: 5,
                price: 2550,
                place_id: 8,
                rate: [],
                type: "شهرالعسل ",
                id: 4,
              },
              {
                title: "بوكيت عرض لشخصين",
                image: "/images/trav.jpg",
                day: 6,
                night: 5,
                price: 2550,
                place_id: 8,
                rate: [],
                type: "شهرالعسل ",
                id: 5,
              },
              {
                title: "بوكيت عرض لشخصين",
                image: "/images/trav.jpg",
                day: 6,
                night: 5,
                price: 2550,
                place_id: 8,
                rate: [],
                type: "عوائل",
                id: 6,
              },
            ],
          },
        ],
      },
      {
        id: 12,
        title: "سيشل ",
        desc: "ماهيه ⚪ برسلين",
        image: "/images/seychelles.jpg",
        ref: "worldpackages/5",
        packages: [
          {
            nav: [
              {
                title: "بوكيت عرض لشخصين",
                image: "/images/trav.jpg",
                locate: "تايلاند",
                day: 6,
                night: 5,
                price: 2550,
                place_id: 8,
                person: 2,

                rate: [
                  // <MdStarRate />,
                  // <MdStarRate />,
                  // <MdStarRate />,
                  // <MdStarRate />,
                  // <MdStarRate />,
                ],
                type: "vip",
                id: 0,
              },
              {
                title: "بوكيت عرض لشخصين",
                image: "/images/trav.jpg",
                day: 6,
                locate: "تايلاند",
                person: 2,
                night: 5,
                price: 2550,
                place_id: 8,
                rate: [
                  // <MdStarRate />,
                  // <MdStarRate />,
                  // <MdStarRate />,
                  // <MdStarRate />,
                  // <MdStarRate />,
                ],
                type: "vip",
                id: 1,
              },
              {
                title: "بوكيت عرض لشخصين",
                image: "/images/trav.jpg",
                day: 6,
                night: 5,
                price: 2550,
                place_id: 8,
                // rate: [<MdStarRate />, <MdStarRate />, <MdStarRate />],
                type: "vip",
                id: 2,
                locate: "تايلاند",
                person: 2,
              },
              {
                title: "بوكيت عرض لشخصين",
                image: "/images/trav.jpg",
                day: 6,
                night: 5,
                price: 2550,
                place_id: 8,
                rate: [],
                type: "شهرالعسل ",
                id: 3,
              },
              {
                title: "بوكيت عرض لشخصين",
                image: "/images/trav.jpg",
                day: 6,
                night: 5,
                price: 2550,
                place_id: 8,
                rate: [],
                type: "شهرالعسل ",
                id: 4,
              },
              {
                title: "بوكيت عرض لشخصين",
                image: "/images/trav.jpg",
                day: 6,
                night: 5,
                price: 2550,
                place_id: 8,
                rate: [],
                type: "شهرالعسل ",
                id: 5,
              },
              {
                title: "بوكيت عرض لشخصين",
                image: "/images/trav.jpg",
                day: 6,
                night: 5,
                price: 2550,
                place_id: 8,
                rate: [],
                type: "عوائل",
                id: 6,
              },
            ],
          },
        ],
      },
      {
        id: 13,
        title: "موريشيوس",
        desc: "",
        image: "/images/mauritius.jpg",
        ref: "worldpackages/5",
        packages: [
          {
            nav: [
              {
                title: "بوكيت عرض لشخصين",
                image: "/images/trav.jpg",
                locate: "تايلاند",
                day: 6,
                night: 5,
                price: 2550,
                place_id: 8,
                person: 2,

                rate: [
                  // <MdStarRate />,
                  // <MdStarRate />,
                  // <MdStarRate />,
                  // <MdStarRate />,
                  // <MdStarRate />,
                ],
                type: "vip",
                id: 0,
              },
              {
                title: "بوكيت عرض لشخصين",
                image: "/images/trav.jpg",
                day: 6,
                locate: "تايلاند",
                person: 2,
                night: 5,
                price: 2550,
                place_id: 8,
                rate: [
                  // <MdStarRate />,
                  // <MdStarRate />,
                  // <MdStarRate />,
                  // <MdStarRate />,
                  // <MdStarRate />,
                ],
                type: "vip",
                id: 1,
              },
              {
                title: "بوكيت عرض لشخصين",
                image: "/images/trav.jpg",
                day: 6,
                night: 5,
                price: 2550,
                place_id: 8,
                // rate: [<MdStarRate />, <MdStarRate />, <MdStarRate />],
                type: "vip",
                id: 2,
                locate: "تايلاند",
                person: 2,
              },
              {
                title: "بوكيت عرض لشخصين",
                image: "/images/trav.jpg",
                day: 6,
                night: 5,
                price: 2550,
                place_id: 8,
                rate: [],
                type: "شهرالعسل ",
                id: 3,
              },
              {
                title: "بوكيت عرض لشخصين",
                image: "/images/trav.jpg",
                day: 6,
                night: 5,
                price: 2550,
                place_id: 8,
                rate: [],
                type: "شهرالعسل ",
                id: 4,
              },
              {
                title: "بوكيت عرض لشخصين",
                image: "/images/trav.jpg",
                day: 6,
                night: 5,
                price: 2550,
                place_id: 8,
                rate: [],
                type: "شهرالعسل ",
                id: 5,
              },
              {
                title: "بوكيت عرض لشخصين",
                image: "/images/trav.jpg",
                day: 6,
                night: 5,
                price: 2550,
                place_id: 8,
                rate: [],
                type: "عوائل",
                id: 6,
              },
            ],
          },
        ],
      },
      {
        id: 14,
        title: "اوزباكستان",
        desc: "طشقند ⚪سمرقند ",
        image: "/images/Uzbekistan.jpg",
        ref: "worldpackages/5",
        packages: [
          {
            nav: [
              {
                title: "بوكيت عرض لشخصين",
                image: "/images/trav.jpg",
                locate: "تايلاند",
                day: 6,
                night: 5,
                price: 2550,
                place_id: 8,
                person: 2,

                rate: [
                  // <MdStarRate />,
                  // <MdStarRate />,
                  // <MdStarRate />,
                  // <MdStarRate />,
                  // <MdStarRate />,
                ],
                type: "vip",
                id: 0,
              },
              {
                title: "بوكيت عرض لشخصين",
                image: "/images/trav.jpg",
                day: 6,
                locate: "تايلاند",
                person: 2,
                night: 5,
                price: 2550,
                place_id: 8,
                rate: [
                  // <MdStarRate />,
                  // <MdStarRate />,
                  // <MdStarRate />,
                  // <MdStarRate />,
                  // <MdStarRate />,
                ],
                type: "vip",
                id: 1,
              },
              {
                title: "بوكيت عرض لشخصين",
                image: "/images/trav.jpg",
                day: 6,
                night: 5,
                price: 2550,
                place_id: 8,
                // rate: [<MdStarRate />, <MdStarRate />, <MdStarRate />],
                type: "vip",
                id: 2,
                locate: "تايلاند",
                person: 2,
              },
              {
                title: "بوكيت عرض لشخصين",
                image: "/images/trav.jpg",
                day: 6,
                night: 5,
                price: 2550,
                place_id: 8,
                rate: [],
                type: "شهرالعسل ",
                id: 3,
              },
              {
                title: "بوكيت عرض لشخصين",
                image: "/images/trav.jpg",
                day: 6,
                night: 5,
                price: 2550,
                place_id: 8,
                rate: [],
                type: "شهرالعسل ",
                id: 4,
              },
              {
                title: "بوكيت عرض لشخصين",
                image: "/images/trav.jpg",
                day: 6,
                night: 5,
                price: 2550,
                place_id: 8,
                rate: [],
                type: "شهرالعسل ",
                id: 5,
              },
              {
                title: "بوكيت عرض لشخصين",
                image: "/images/trav.jpg",
                day: 6,
                night: 5,
                price: 2550,
                place_id: 8,
                rate: [],
                type: "عوائل",
                id: 6,
              },
            ],
          },
        ],
      },
      {
        id: 15,
        title: "سويسرا ",
        desc: "زيورخ⚪ سانت⚪ مورتيز⚪ لوغانو⚪ ⚪لوسرن⚪ جينيف⚪ مونترو ⚪انترلاكن ⚪زيرمات",
        image: "/images/swiss.jpg",
        ref: "worldpackages/5",
        packages: [
          {
            nav: [
              {
                title: "بوكيت عرض لشخصين",
                image: "/images/trav.jpg",
                locate: "تايلاند",
                day: 6,
                night: 5,
                price: 2550,
                place_id: 8,
                person: 2,

                rate: [
                  // <MdStarRate />,
                  // <MdStarRate />,
                  // <MdStarRate />,
                  // <MdStarRate />,
                  // <MdStarRate />,
                ],
                type: "vip",
                id: 0,
              },
              {
                title: "بوكيت عرض لشخصين",
                image: "/images/trav.jpg",
                day: 6,
                locate: "تايلاند",
                person: 2,
                night: 5,
                price: 2550,
                place_id: 8,
                rate: [
                  // <MdStarRate />,
                  // <MdStarRate />,
                  // <MdStarRate />,
                  // <MdStarRate />,
                  // <MdStarRate />,
                ],
                type: "vip",
                id: 1,
              },
              {
                title: "بوكيت عرض لشخصين",
                image: "/images/trav.jpg",
                day: 6,
                night: 5,
                price: 2550,
                place_id: 8,
                // rate: [<MdStarRate />, <MdStarRate />, <MdStarRate />],
                type: "vip",
                id: 2,
                locate: "تايلاند",
                person: 2,
              },
              {
                title: "بوكيت عرض لشخصين",
                image: "/images/trav.jpg",
                day: 6,
                night: 5,
                price: 2550,
                place_id: 8,
                rate: [],
                type: "شهرالعسل ",
                id: 3,
              },
              {
                title: "بوكيت عرض لشخصين",
                image: "/images/trav.jpg",
                day: 6,
                night: 5,
                price: 2550,
                place_id: 8,
                rate: [],
                type: "شهرالعسل ",
                id: 4,
              },
              {
                title: "بوكيت عرض لشخصين",
                image: "/images/trav.jpg",
                day: 6,
                night: 5,
                price: 2550,
                place_id: 8,
                rate: [],
                type: "شهرالعسل ",
                id: 5,
              },
              {
                title: "بوكيت عرض لشخصين",
                image: "/images/trav.jpg",
                day: 6,
                night: 5,
                price: 2550,
                place_id: 8,
                rate: [],
                type: "عوائل",
                id: 6,
              },
            ],
          },
        ],
      },
    ],
  },
];
