export const hotels = [
  { id:0,
    title: "مكه",
    list: [
      {
        hotelName: "سويس أوتيل مكة",
        rate: 5,
        location: "وقف الملك عبد العزيز",
        distance: "0.52 كم من المسجد الحرام",
        review: "جيد جدا",
        timer:'10 دقايق',
        image: "/images/swissHotel.webp",
        id: 1,
      },
      {
        hotelName: "فندق برج ساعة مكة الملكي فيرمونت",
        rate: 5,
        location: "وقف الملك عبد العزيز",
        distance: "0.54 كم من المسجد الحرام",
        review: "جيد جدا",
        timer:'14 دقايق',
        image: "/images/swissHotel.webp",
        id: 2,
      },
      {
        hotelName: "العنوان جبل عمر، مكة",
        rate: 5,
        location: "طريق الأمير محمد بن سلمان",
        distance: "0.69 كم من المسجد الحرام",
        review: "ممتاز",
        timer:'16 دقايق',
        image: "/images/enwanHotel.webp",
        id: 3,
      },
      {
        hotelName: "سويس أوتل المقام مكة",
        rate: 5,
        location: "وقف الملك عبد العزيز برج إف",
        distance: "0.56 كم من المسجد الحرام",
        review: "جيد جدا",
        timer:'10 دقايق',
        image: "/images/swissHotel.webp",
        id: 4,
      },
      {
        hotelName: "فندق أعيان معابدة",
        rate: 3,
        location: "الخنساء، 24238 مكة المكرمة، المملكة العربية السعودية",
        distance: "2.4 كم من المسجد الحرام",
        review: "جيد جدا",
        timer:'30 دقايق',
        image: "/images/aaiyanHotel.webp",
        id: 5,
      },
      {
        hotelName: "مادا زاد التيسيير",
        rate: 3,
        location: "بئر طوى، حي التيسير، مكة المكرمة، المملكة العربية السعودية",
        distance: "1.2 كم من المسجد الحرام",
        review: "جيد جدا",
        timer:'20 دقايق',
        image: "/images/ramadaHotel.webp",
        id: 6,
      },
      {
        hotelName: "فندق العليان الماسي - المعابده",
        rate: 3,
        location:
          "حي الخنساء, شارع الابطح, 24238 مكة المكرمة, المملكة العربية السعودية",
        distance: "2.5 كم من المسجد الحرام",
        review: "جيد جدا",
        timer:'30 دقايق',
        image: "/images/alAliyanHotel.webp",
        id: 7,
      },
      {
        hotelName: "فندق بولمان زمزم مكة",
        rate: 5,
        location: "أبراج البيت",
        distance: "0.42 كم من المسجد الحرام",
        review: "جيد ",
        timer:'10 دقايق',
        image: "/images/bolmanHotel.webp",
        id: 8,
      },
      {
        hotelName: "حياة ريجنسي مكة جبل عمر ",
        rate: 5,
        location: "جبل عمر، شارع إبراهيم الخليل",
        distance: "0.44 كم من المسجد الحرام",
        review: "ممتاز",
        timer:'10 دقايق',
        image: "/images/hayahRegHotel.webp",
        id: 9,
      },
      {
        hotelName: "فندق ميزاب السلطان",
        rate: "4",
        location:
          "طريق الأمير سلطان، حي العزيزية الجنوبي، مكة المكرمة، المملكة العربية السعودية",
        distance: "0.52 كم من المسجد الحرام",
        review: "جيد جدا",
        timer:'10 دقايق',
        image: "/images/mizabHotel.webp",
        id: 10,
      },
    ],
  },
  { id:1,
    title: "القاهرة",
    list: [
      {
        hotelName: "سويس أوتيل مكة",
        rate: 5,
        location: "وقف الملك عبد العزيز",
        distance: "0.52 كم من المسجد الحرام",
        review: "جيد جدا",
        timer:'10 دقايق',
        image: "/images/swissHotel.webp",
        id: 1,
      },
      {
        hotelName: "فندق برج ساعة مكة الملكي فيرمونت",
        rate: 5,
        location: "وقف الملك عبد العزيز",
        distance: "0.54 كم من المسجد الحرام",
        review: "جيد جدا",
        timer:'10 دقايق',
        image: "/images/swissHotel.webp",
        id: 2,
      },
      {
        hotelName: "العنوان جبل عمر، مكة",
        rate: 5,
        location: "طريق الأمير محمد بن سلمان",
        distance: "0.69 كم من المسجد الحرام",
        review: "ممتاز",
        timer:'10 دقايق',
        image: "/images/enwanHotel.webp",
        id: 3,
      },
      {
        hotelName: "سويس أوتل المقام مكة",
        rate: 5,
        location: "وقف الملك عبد العزيز برج إف",
        distance: "0.56 كم من المسجد الحرام",
        review: "جيد جدا",
        timer:'10 دقايق',
        image: "/images/swissHotel.webp",
        id: 4,
      },
      {
        hotelName: "فندق أعيان معابدة",
        rate: 3,
        location: "الخنساء، 24238 مكة المكرمة، المملكة العربية السعودية",
        distance: "2.4 كم من المسجد الحرام",
        review: "جيد جدا",
        timer:'10 دقايق',
        image: "/images/aaiyanHotel.webp",
        id: 5,
      },
      {
        hotelName: "مادا زاد التيسيير",
        rate: 3,
        location: "بئر طوى، حي التيسير، مكة المكرمة، المملكة العربية السعودية",
        distance: "1.2 كم من المسجد الحرام",
        review: "جيد جدا",
        timer:'10 دقايق',
        image: "/images/ramadaHotel.webp",
        id: 6,
      },
      {
        hotelName: "فندق العليان الماسي - المعابده",
        rate: 3,
        location:
          "حي الخنساء, شارع الابطح, 24238 مكة المكرمة, المملكة العربية السعودية",
        distance: "2.5 كم من المسجد الحرام",
        review: "جيد جدا",
        timer:'10 دقايق',
        image: "/images/alAliyanHotel.webp",
        id: 7,
      },
      {
        hotelName: "فندق بولمان زمزم مكة",
        rate: 5,
        location: "أبراج البيت",
        distance: "0.42 كم من المسجد الحرام",
        review: "جيد ",
        timer:'10 دقايق',
        image: "/images/bolmanHotel.webp",
        id: 8,
      },
      {
        hotelName: "حياة ريجنسي مكة جبل عمر ",
        rate: 5,
        location: "جبل عمر، شارع إبراهيم الخليل",
        distance: "0.44 كم من المسجد الحرام",
        review: "ممتاز",
        timer:'10 دقايق',
        image: "/images/hayahRegHotel.webp",
        id: 9,
      },
      {
        hotelName: "فندق ميزاب السلطان",
        rate: "4",
        location:
          "طريق الأمير سلطان، حي العزيزية الجنوبي، مكة المكرمة، المملكة العربية السعودية",
        distance: "0.52 كم من المسجد الحرام",
        review: "جيد جدا",
        timer:'10 دقايق',
        image: "/images/mizabHotel.webp",
        id: 10,
      },
    ],
  },
  { id:2,
    title: "لندن",
    list: [
      {
        hotelName: "سويس أوتيل مكة",
        rate: 5,
        location: "وقف الملك عبد العزيز",
        distance: "0.52 كم من المسجد الحرام",
        review: "جيد جدا",
        timer:'10 دقايق',
        image: "/images/swissHotel.webp",
        id: 1,
      },
      {
        hotelName: "فندق برج ساعة مكة الملكي فيرمونت",
        rate: 5,
        location: "وقف الملك عبد العزيز",
        distance: "0.54 كم من المسجد الحرام",
        review: "جيد جدا",
        timer:'10 دقايق',
        image: "/images/swissHotel.webp",
        id: 2,
      },
      {
        hotelName: "العنوان جبل عمر، مكة",
        rate: 5,
        location: "طريق الأمير محمد بن سلمان",
        distance: "0.69 كم من المسجد الحرام",
        review: "ممتاز",
        timer:'10 دقايق',
        image: "/images/enwanHotel.webp",
        id: 3,
      },
      {
        hotelName: "سويس أوتل المقام مكة",
        rate: 5,
        location: "وقف الملك عبد العزيز برج إف",
        distance: "0.56 كم من المسجد الحرام",
        review: "جيد جدا",
        timer:'10 دقايق',
        image: "/images/swissHotel.webp",
        id: 4,
      },
      {
        hotelName: "فندق أعيان معابدة",
        rate: 3,
        location: "الخنساء، 24238 مكة المكرمة، المملكة العربية السعودية",
        distance: "2.4 كم من المسجد الحرام",
        review: "جيد جدا",
        timer:'10 دقايق',
        image: "/images/aaiyanHotel.webp",
        id: 5,
      },
      {
        hotelName: "مادا زاد التيسيير",
        rate: 3,
        location: "بئر طوى، حي التيسير، مكة المكرمة، المملكة العربية السعودية",
        distance: "1.2 كم من المسجد الحرام",
        review: "جيد جدا",
        timer:'10 دقايق',
        image: "/images/ramadaHotel.webp",
        id: 6,
      },
      {
        hotelName: "فندق العليان الماسي - المعابده",
        rate: 3,
        location:
          "حي الخنساء, شارع الابطح, 24238 مكة المكرمة, المملكة العربية السعودية",
        distance: "2.5 كم من المسجد الحرام",
        review: "جيد جدا",
        timer:'10 دقايق',
        image: "/images/alAliyanHotel.webp",
        id: 7,
      },
      {
        hotelName: "فندق بولمان زمزم مكة",
        rate: 5,
        location: "أبراج البيت",
        distance: "0.42 كم من المسجد الحرام",
        review: "جيد ",
        timer:'10 دقايق',
        image: "/images/bolmanHotel.webp",
        id: 8,
      },
      {
        hotelName: "حياة ريجنسي مكة جبل عمر ",
        rate: 5,
        location: "جبل عمر، شارع إبراهيم الخليل",
        distance: "0.44 كم من المسجد الحرام",
        review: "ممتاز",
        timer:'10 دقايق',
        image: "/images/hayahRegHotel.webp",
        id: 9,
      },
      {
        hotelName: "فندق ميزاب السلطان",
        rate: "4",
        location:
          "طريق الأمير سلطان، حي العزيزية الجنوبي، مكة المكرمة، المملكة العربية السعودية",
        distance: "0.52 كم من المسجد الحرام",
        review: "جيد جدا",
        timer:'10 دقايق',
        image: "/images/mizabHotel.webp",
        id: 10,
      },
    ],
  },
  { id:3,
    title: "ميونخ",
    list: [
      {
        hotelName: "سويس أوتيل مكة",
        rate: 5,
        location: "وقف الملك عبد العزيز",
        distance: "0.52 كم من المسجد الحرام",
        review: "جيد جدا",
        timer:'10 دقايق',
        image: "/images/swissHotel.webp",
        id: 1,
      },
      {
        hotelName: "فندق برج ساعة مكة الملكي فيرمونت",
        rate: 5,
        location: "وقف الملك عبد العزيز",
        distance: "0.54 كم من المسجد الحرام",
        review: "جيد جدا",
        timer:'10 دقايق',
        image: "/images/swissHotel.webp",
        id: 2,
      },
      {
        hotelName: "العنوان جبل عمر، مكة",
        rate: 5,
        location: "طريق الأمير محمد بن سلمان",
        distance: "0.69 كم من المسجد الحرام",
        review: "ممتاز",
        timer:'10 دقايق',
        image: "/images/enwanHotel.webp",
        id: 3,
      },
      {
        hotelName: "سويس أوتل المقام مكة",
        rate: 5,
        location: "وقف الملك عبد العزيز برج إف",
        distance: "0.56 كم من المسجد الحرام",
        review: "جيد جدا",
        timer:'10 دقايق',
        image: "/images/swissHotel.webp",
        id: 4,
      },
      {
        hotelName: "فندق أعيان معابدة",
        rate: 3,
        location: "الخنساء، 24238 مكة المكرمة، المملكة العربية السعودية",
        distance: "2.4 كم من المسجد الحرام",
        review: "جيد جدا",
        timer:'10 دقايق',
        image: "/images/aaiyanHotel.webp",
        id: 5,
      },
      {
        hotelName: "مادا زاد التيسيير",
        rate: 3,
        location: "بئر طوى، حي التيسير، مكة المكرمة، المملكة العربية السعودية",
        distance: "1.2 كم من المسجد الحرام",
        review: "جيد جدا",
        timer:'10 دقايق',
        image: "/images/ramadaHotel.webp",
        id: 6,
      },
      {
        hotelName: "فندق العليان الماسي - المعابده",
        rate: 3,
        location:
          "حي الخنساء, شارع الابطح, 24238 مكة المكرمة, المملكة العربية السعودية",
        distance: "2.5 كم من المسجد الحرام",
        review: "جيد جدا",
        timer:'10 دقايق',
        image: "/images/alAliyanHotel.webp",
        id: 7,
      },
      {
        hotelName: "فندق بولمان زمزم مكة",
        rate: 5,
        location: "أبراج البيت",
        distance: "0.42 كم من المسجد الحرام",
        review: "جيد ",
        timer:'10 دقايق',
        image: "/images/bolmanHotel.webp",
        id: 8,
      },
      {
        hotelName: "حياة ريجنسي مكة جبل عمر ",
        rate: 5,
        location: "جبل عمر، شارع إبراهيم الخليل",
        distance: "0.44 كم من المسجد الحرام",
        review: "ممتاز",
        timer:'10 دقايق',
        image: "/images/hayahRegHotel.webp",
        id: 9,
      },
      {
        hotelName: "فندق ميزاب السلطان",
        rate: "4",
        location:
          "طريق الأمير سلطان، حي العزيزية الجنوبي، مكة المكرمة، المملكة العربية السعودية",
        distance: "0.52 كم من المسجد الحرام",
        review: "جيد جدا",
        timer:'10 دقايق',
        image: "/images/mizabHotel.webp",
        id: 10,
      },
    ],
  },
  { id:4,
    title: "رياض",
    list: [
      {
        hotelName: "سويس أوتيل مكة",
        rate: 5,
        location: "وقف الملك عبد العزيز",
        distance: "0.52 كم من المسجد الحرام",
        review: "جيد جدا",
        timer:'10 دقايق',
        image: "/images/swissHotel.webp",
        id: 1,
      },
      {
        hotelName: "فندق برج ساعة مكة الملكي فيرمونت",
        rate: 5,
        location: "وقف الملك عبد العزيز",
        distance: "0.54 كم من المسجد الحرام",
        review: "جيد جدا",
        timer:'10 دقايق',
        image: "/images/swissHotel.webp",
        id: 2,
      },
      {
        hotelName: "العنوان جبل عمر، مكة",
        rate: 5,
        location: "طريق الأمير محمد بن سلمان",
        distance: "0.69 كم من المسجد الحرام",
        review: "ممتاز",
        timer:'10 دقايق',
        image: "/images/enwanHotel.webp",
        id: 3,
      },
      {
        hotelName: "سويس أوتل المقام مكة",
        rate: 5,
        location: "وقف الملك عبد العزيز برج إف",
        distance: "0.56 كم من المسجد الحرام",
        review: "جيد جدا",
        timer:'10 دقايق',
        image: "/images/swissHotel.webp",
        id: 4,
      },
      {
        hotelName: "فندق أعيان معابدة",
        rate: 3,
        location: "الخنساء، 24238 مكة المكرمة، المملكة العربية السعودية",
        distance: "2.4 كم من المسجد الحرام",
        review: "جيد جدا",
        timer:'10 دقايق',
        image: "/images/aaiyanHotel.webp",
        id: 5,
      },
      {
        hotelName: "مادا زاد التيسيير",
        rate: 3,
        location: "بئر طوى، حي التيسير، مكة المكرمة، المملكة العربية السعودية",
        distance: "1.2 كم من المسجد الحرام",
        review: "جيد جدا",
        timer:'10 دقايق',
        image: "/images/ramadaHotel.webp",
        id: 6,
      },
      {
        hotelName: "فندق العليان الماسي - المعابده",
        rate: 3,
        location:
          "حي الخنساء, شارع الابطح, 24238 مكة المكرمة, المملكة العربية السعودية",
        distance: "2.5 كم من المسجد الحرام",
        review: "جيد جدا",
        timer:'10 دقايق',
        image: "/images/alAliyanHotel.webp",
        id: 7,
      },
      {
        hotelName: "فندق بولمان زمزم مكة",
        rate: 5,
        location: "أبراج البيت",
        distance: "0.42 كم من المسجد الحرام",
        review: "جيد ",
        timer:'10 دقايق',
        image: "/images/bolmanHotel.webp",
        id: 8,
      },
      {
        hotelName: "حياة ريجنسي مكة جبل عمر ",
        rate: 5,
        location: "جبل عمر، شارع إبراهيم الخليل",
        distance: "0.44 كم من المسجد الحرام",
        review: "ممتاز",
        timer:'10 دقايق',
        image: "/images/hayahRegHotel.webp",
        id: 9,
      },
      {
        hotelName: "فندق ميزاب السلطان",
        rate: "4",
        location:
          "طريق الأمير سلطان، حي العزيزية الجنوبي، مكة المكرمة، المملكة العربية السعودية",
        distance: "0.52 كم من المسجد الحرام",
        review: "جيد جدا",
        timer:'10 دقايق',
        image: "/images/mizabHotel.webp",
        id: 10,
      },
    ],
  },
  { id:5,
    title: "جدة",
    list: [
      {
        hotelName: "سويس أوتيل مكة",
        rate: 5,
        location: "وقف الملك عبد العزيز",
        distance: "0.52 كم من المسجد الحرام",
        review: "جيد جدا",
        timer:'10 دقايق',
        image: "/images/swissHotel.webp",
        id: 1,
      },
      {
        hotelName: "فندق برج ساعة مكة الملكي فيرمونت",
        rate: 5,
        location: "وقف الملك عبد العزيز",
        distance: "0.54 كم من المسجد الحرام",
        review: "جيد جدا",
        timer:'10 دقايق',
        image: "/images/swissHotel.webp",
        id: 2,
      },
      {
        hotelName: "العنوان جبل عمر، مكة",
        rate: 5,
        location: "طريق الأمير محمد بن سلمان",
        distance: "0.69 كم من المسجد الحرام",
        review: "ممتاز",
        timer:'10 دقايق',
        image: "/images/enwanHotel.webp",
        id: 3,
      },
      {
        hotelName: "سويس أوتل المقام مكة",
        rate: 5,
        location: "وقف الملك عبد العزيز برج إف",
        distance: "0.56 كم من المسجد الحرام",
        review: "جيد جدا",
        timer:'10 دقايق',
        image: "/images/swissHotel.webp",
        id: 4,
      },
      {
        hotelName: "فندق أعيان معابدة",
        rate: 3,
        location: "الخنساء، 24238 مكة المكرمة، المملكة العربية السعودية",
        distance: "2.4 كم من المسجد الحرام",
        review: "جيد جدا",
        timer:'10 دقايق',
        image: "/images/aaiyanHotel.webp",
        id: 5,
      },
      {
        hotelName: "مادا زاد التيسيير",
        rate: 3,
        location: "بئر طوى، حي التيسير، مكة المكرمة، المملكة العربية السعودية",
        distance: "1.2 كم من المسجد الحرام",
        review: "جيد جدا",
        timer:'10 دقايق',
        image: "/images/ramadaHotel.webp",
        id: 6,
      },
      {
        hotelName: "فندق العليان الماسي - المعابده",
        rate: 3,
        location:
          "حي الخنساء, شارع الابطح, 24238 مكة المكرمة, المملكة العربية السعودية",
        distance: "2.5 كم من المسجد الحرام",
        review: "جيد جدا",
        timer:'10 دقايق',
        image: "/images/alAliyanHotel.webp",
        id: 7,
      },
      {
        hotelName: "فندق بولمان زمزم مكة",
        rate: 5,
        location: "أبراج البيت",
        distance: "0.42 كم من المسجد الحرام",
        review: "جيد ",
        timer:'10 دقايق',
        image: "/images/bolmanHotel.webp",
        id: 8,
      },
      {
        hotelName: "حياة ريجنسي مكة جبل عمر ",
        rate: 5,
        location: "جبل عمر، شارع إبراهيم الخليل",
        distance: "0.44 كم من المسجد الحرام",
        review: "ممتاز",
        timer:'10 دقايق',
        image: "/images/hayahRegHotel.webp",
        id: 9,
      },
      {
        hotelName: "فندق ميزاب السلطان",
        rate: "4",
        location:
          "طريق الأمير سلطان، حي العزيزية الجنوبي، مكة المكرمة، المملكة العربية السعودية",
        distance: "0.52 كم من المسجد الحرام",
        review: "جيد جدا",
        timer:'10 دقايق',
        image: "/images/mizabHotel.webp",
        id: 10,
      },
    ],
  },
];
