import Head from "next/head";
import Image from "next/image";
import { Inter } from "next/font/google";
import styles from "@/styles/Home.module.css";
import { Layout } from "@/layout/Layout";
import Navbar from "@/components/NavBar/Navbar";
import Hero from "@/components/Hero/Hero";
import ACard from "@/components/ACard/ACard";
import { offers, worldHotel } from "@/constants/constants";
import BCard from "@/components/BCard/BCard";
import FooterBar from "@/components/FooterBar/FooterBar";
import FlipCard from "@/components/flipCard/FlipCard";
import FlipContainer from "@/components/FlipContainer/FlipContainer";

import FooterContainer from "@/components/footer/FooterContainer";
import ProgramCard2 from "@/components/pro2/ProgramCard2";

export default function Home() {
  return (
    <>
      <Head>
        <title>Wesam Elnagah</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      
      <Layout>
        <Hero />
        <Navbar />
        <ACard
          arryName={offers}
          compTitle="عروض مميزة منّا لك"
          sliderName="offerSlider"
        />
        <BCard
          arryName={worldHotel}
          compTitle="أفضل الفنادق العالمية"
          sliderName="worldHotelSlider"
        />
        <BCard
          arryName={worldHotel}
          compTitle="أفضل الفنادق العالمية"
          sliderName="worldHotelSlider2"
        />
        <BCard
          arryName={worldHotel}
          compTitle="دليلك لأشهر الوجهات السياحية العالمية"
          sliderName="travelSlider"
        />
        <ACard
          arryName={offers}
          compTitle="اكتشف أجمل ما في المملكة العربية السعودية"
          sliderName="TheBestSlider"
        />
        <FlipContainer />
        <ProgramCard2/>
      </Layout>
    </>
  );
}
